url: http://aba-icc.org
sitename: 'ABA-ICC PROJECT'
description: 'ABA Center for Human Rights'
# do not include  https://github.com/...
repo: 'sonnetmedia/aba-icc.org'
branch: master
default_author: "Bud Parr"
source: src

#Jekyll Options
# if using more than one Jekyll instance on your local machine
port: 4049
permalink:  pretty

# Dependencies
markdown: kramdown
include: ['_pages']
# relative_permalinks: false # won't need this as of 2.0: Deprecation: Starting in 2.0, permalinks for pages in subfolders must be relative to the site source directory, not the parent directory. Also will change exclude directory
exclude: ['readme.md','license.md','Gemfile','links.jsonp', 'CNAME', 'rakefile', 'bower.json', 'node_modules', 'content-list.yaml']
# gems:
  #- jekyll-sitemap

# dev options (true/false)
# if site is in production, 'production: true'
production: false
include_jquery: false
use_jquery_cdn: false
include_addthis_sharing: true
bust_css_cache: true

# options (data)
google_analytics_id: UA-XXXXXXX-X
disqus_id:
addthis_id: "ra-53c565a74f2c5c5b"
# CONTACT FORM http://getsimpleform.com/
simple_form_api_token:

# options (social)
# facebook_id:
twitter_id: budparr

sass:
    style: :expanded
    sass_dir: assets/css/_sass

# source: content

collections:
 the-aba-icc-project:
  collection_name: "The ABA-ICC Project"
  output: true
  permalink: /:collection/:path/
 international-criminal-justice-today:
  collection_name: "International Criminal Justice Today"
  output: true
  permalink: /:path/
 about-the-icc:
  collection_name: About the ICC
  output: true
  permalink: /:path/
 rights-of-the-participants:
  output: true
  permalink: /:collection/:path/
 evolution-of-international-criminal-justice:
  collection_name: "The Evolution of International Criminal Justice"
  permalink: /:collection/:path/
  output: true
  splash_image: "Nuremberg_Trials.jpg"
  description: "A timeline to explore the evolution of international criminal justice and learn about the multiple and varied influences that have shaped this field of international affairs."
 arguendo:
  collection_name: "Arguendo"
  output: true
  description: "Experts debate issues of the day on International Criminal Justice"
  permalink: /:collection/:path/
  layout: arguendo
  class: arguendo
 board-of-advisors:
  collection_name: "Board of Advisors"
  main_page_link: "/the-aba-icc-project/board-of-advisors/"
  output: true
  permalink: /:collection/:path/

defaults:
 - 
  scope:
   path: ''
   type: page
  values:
   layout: page
 - 
  scope:
   path: ""
   type: 'board-of-advisors'
  values:
   layout: page
 -
  scope:
   path: "news"
   type: "post" # empty string for all files
  values:
   layout: "article"
   category: "Event"
 -
  scope:
   path: ""
   type: "the-aba-icc-project" # empty string for all files
  values:
   sharing: false
   comments: false
 -
  scope:
   path: "arguendo"
  values:
   layout: "arguendo"
 -
  scope:
   path: ""
   type: "international-criminal-justice-today"
  values:
   layout: "page"
