url: https://www.aba-icc.org
title: "The ABA's ICC Project"
description: "American Bar Association's International Criminal Court Project"
twitter:
  username: ABAICCProject
logo: /assets/images/logo-aba-icc_144xb.png
case_statuses:
 - "Pre-trial"
 - "Trial Ongoing"
 - "Case Terminated"
 - "Trial Adjourned"
 - "Trial Complete: Acquitted"
 - "Trial Complete: Sentenced"
 - "Guilty Plea"
 - "Guilty Plea: Sentenced"

phases:
  - "Preliminary Examinations, Initial Assessment"
  - "Preliminary Examinations, Admissibility Assessment"
  - "Preliminary Examinations, Subject Matter Jurisdiction Assessement"
  - "Preliminary Examinations, Closed - Decision Not to Proceed"
  - "Situations & Cases"

processes:
  - ''
  - jurisdictional-triggers
  - referrals-and-communication
  - preliminary-examination
  - investigation
  - arrest-warrant-and-summons
  - confirmation-of-charges
  - trial-and-appeal
  - sentencing-and-reparations

sort_order:
  - 01
  - 02
  - 03
  - 04
  - 05
  - 06
  - 07
  - 08
  - 09
  - 10

## DO NOT EDIT BELOW THIS LINE

jekyll_get:
  data: news
  json: 'https://www.international-criminal-justice-today.org/api/icjt-news.json'


version: 3.0.3
full_rebuild: true
image_url: https://aba-icc.imgix.net
kramdown:
  input: GFM
future: false
gems:
  - jekyll-seo-tag
  #- jekyll-sitemap
incremental: true
timezone: Etc/Zulu
port: 4049
plugins_dir:  ./_app/_plugins
layouts_dir:  ./_app/_layouts
includes_dir: ./_app/_includes

exclude:
  - readme.md
  - todo.md
  - license.md
  - Gemfile
  - Gemfile.lock
  - bower.json
  - CNAME
  - node_modules
  - sass
  - gulpfile.js
  - package.json
  - javascript
  - vendor

images: /assets/img/
# dev options (true/false)
# if site is in production, 'production: true'
production: true
bust_css_cache: false

# options (data)
google_analytics_id: UA-51919693-2
addthis_id: "ra-53c565a74f2c5c5b"

# source: content

collections:
  about-the-icc:
    output: true
    permalink: '/:collection/:path/'
    name: "About the ICC"
  accuseds:
    output: true
    permalink: '/accused/:path/'
  board-of-advisors:
    output: true
    permalink: '/:collection/:path/'
  cases:
    output: true
    permalink: '/:collection/case/:path/'
    food: "bars"
  cases-charges:
    output: false
    permalink: '/:collection/:path/'
  cases-events:
    output: false
    permalink: '/:collection/:path/'
  countries:
    output: true
    permalink: '/country/:path/'
  events:
    output: true
    permalink: '/:collection/:path/'
  evolution-of-international-criminal-justice:
    output: false
  situations:
    output: true
    permalink: '/:collection/:path/'
  staff:
    output: true
    permalink: '/:collection/:path/'
  structure-of-the-icc:
    output: false
    permalink: 'about-the-icc/structure-of-the-icc/#:slug'
  the-aba-icc-project:
    output: true
    permalink: '/:collection/:path/'
  cases-test1:
    output: false
  cases-test2:
    output: false
  how-the-court-works:
    output: true
    #permalink: '/:collection/:name/'  
    permalink: '/:collection/:path/'  

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "page"
      collectionName: "Updates"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'about-the-icc'
    values:
      layout: "page"
      collectionName: "About the ICC"
      menu: 'about-the-icc'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'accuseds'
    values:
      layout: "accused"
      collectionName: "Accused"
      menu: 'about-the-icc'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'board-of-advisors'
    values:
      layout: "page"
      collectionName: "Board of Advisors"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'cases'
    values:
      layout: "case"
      collectionName: "Cases"
      menu: 'about-the-icc'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'cases-charges'
    values:
      exclude_from_search: true
      _comments:
        youtube_id: 'Use the ID of the video only, not the embed code'      
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'cases-events'
    values:
      exclude_from_search: true
      _comments:
        youtube_id: 'Use the ID of the video only, not the embed code'      
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'countries'
    values:
      layout: "country"
      collectionName: "Country"
      menu: 'about-the-icc'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'evolution-of-international-criminal-justice'
    values:
      exclude_from_search: true
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'situations'
    values:
      layout: "page"
      collectionName: "Situation & Cases"
      menu: 'about-the-icc'
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "staff"
    values:
      layout: "page"
      collectionName: "Staff"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'the-aba-icc-project'
    values:
      layout: "page"
      collectionName: "The ABA's ICC Project"
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: 'cases-test2'
    values:
      exclude_from_search: true

compress_html:
  ignore:
    envs: [development]
  profile: false
